#!/usr/bin/env Rscript
# build_concepts_ledger.R — regenerate the canonical/alternate ledger inside
# docs/concepts.md from data/catalog.json + data/categories.json.
#
# Only the block between <!-- LEDGER:START --> and <!-- LEDGER:END --> is rewritten;
# the surrounding prose (model, dropped-series rationale, frequency policy) is
# hand-maintained. This kills the drift where a `canonical` flip in a datasheet
# left the ledger stating the old decision. Run from repo root.

suppressWarnings(suppressMessages(library(jsonlite)))
root <- normalizePath(file.path(dirname(sub("--file=", "",
  grep("--file=", commandArgs(FALSE), value = TRUE)[1])), ".."))
`%||%` <- function(a, b) if (is.null(a)) b else a

cat_rows <- fromJSON(file.path(root, "data", "catalog.json"), simplifyVector = FALSE)
cats     <- fromJSON(file.path(root, "data", "categories.json"), simplifyVector = FALSE)
# schema 1.1 tolerant read (bare string | label object | {name: label object})
# schema 1.1: `concept` may be a bare "Group / Leaf" string or an object
# carrying that string plus the resolved i18n leaf. The grouping logic wants
# the English "Group / Leaf" either way.
conc_en <- function(x) if (is.list(x)) (x$en %||% "") else (x %||% "")
disp <- function(x) {
  if (is.null(x) || length(x) == 0) return("")
  if (is.character(x)) return(as.character(x)[1])
  if (is.list(x)) {
    if (!is.null(x$name)) return(disp(x$name))
    return(as.character(if (!is.null(x$en)) x$en else x[[1]])[1])
  }
  as.character(x)[1]
}

order    <- vapply(cats, function(c) disp(c$name), "")

grp_leaf <- function(concept) {
  parts <- trimws(strsplit(concept %||% "Other /", "/", fixed = TRUE)[[1]])
  list(group = parts[1], leaf = if (length(parts) > 1) paste(parts[-1], collapse = " / ") else "")
}
src_short <- function(s) {
  if (is.list(s)) s <- s$name$en %||% s$name %||% ""
  abbr <- c("Swiss National Bank" = "SNB", "Swiss Federal Statistical Office" = "FSO",
            "State Secretariat for Economic Affairs" = "SECO",
            "Federal Finance Administration" = "FFA", "KOF Swiss Economic Institute" = "KOF")
  for (k in names(abbr)) if (grepl(k, s, fixed = TRUE)) return(abbr[[k]])
  s
}
tag <- function(r) {
  feat <- disp(r$featured)          # bare string or i18n object (schema 1.1)
  star <- if (nzchar(feat) && !identical(feat, "NA")) " ★" else ""
  sprintf("`%s` (%s)%s", r$id, src_short(disp(r$source)), star)
}

rows <- lapply(cat_rows, function(r) { gl <- grp_leaf(conc_en(r$concept)); c(r, gl) })

lines <- c(
  "<!-- LEDGER:START — GENERATED by dev/build_concepts_ledger.R; do not edit by hand -->",
  paste0("_Canonical series and labelled alternates per concept, grouped into the ", length(order),
         " overview categories (order from `data/categories.json`). ★ = curated highlight._"),
  ""
)
for (g in order) {
  members <- Filter(function(r) r$group == g, rows)
  if (!length(members)) next
  lines <- c(lines, sprintf("### %s", g),
             "| Concept | Canonical | Alternates |", "|---|---|---|")
  leaves <- unique(vapply(members, function(r) r$leaf, ""))
  for (lf in leaves) {
    ms  <- Filter(function(r) r$leaf == lf, members)
    can <- Filter(function(r) isTRUE(r$canonical), ms)
    alt <- Filter(function(r) !isTRUE(r$canonical), ms)
    can_s <- if (length(can)) paste(vapply(can, tag, ""), collapse = ", ") else "—"
    alt_s <- if (length(alt)) paste(vapply(alt, tag, ""), collapse = ", ") else "—"
    lines <- c(lines, sprintf("| %s | %s | %s |", if (nzchar(lf)) lf else "—", can_s, alt_s))
  }
  lines <- c(lines, "")
}
lines <- c(lines, "<!-- LEDGER:END -->")

doc <- readLines(file.path(root, "docs", "concepts.md"), warn = FALSE)
s <- grep("<!-- LEDGER:START", doc, fixed = TRUE)
e <- grep("<!-- LEDGER:END -->", doc, fixed = TRUE)
if (!length(s) || !length(e)) stop("LEDGER markers not found in docs/concepts.md")
doc <- c(doc[seq_len(s[1] - 1)], lines, doc[(e[1] + 1):length(doc)])
writeLines(doc, file.path(root, "docs", "concepts.md"))
cat(sprintf("regenerated ledger: %d categories, %d datasets\n", length(order), length(cat_rows)))
