#!/usr/bin/env Rscript
# build_catalog_md.R — generate CATALOG.md from data/catalog.json.
#
# A human-readable overview of every dataset, grouped by concept (Group / Leaf).
# Each row: id, title, source, frequency, coverage (start..end), license.
# Run from the repo root: Rscript dev/build_catalog_md.R

suppressWarnings(suppressMessages(library(jsonlite)))

root <- normalizePath(file.path(dirname(sub("--file=", "",
  grep("--file=", commandArgs(FALSE), value = TRUE)[1])), ".."))
if (length(root) == 0 || is.na(root)) root <- getwd()

catalog_path <- file.path(root, "data", "catalog.json")
out_path     <- file.path(root, "CATALOG.md")

cat <- fromJSON(catalog_path, simplifyVector = FALSE)

# license code -> display label. schema 1.1 ships the shared vocabulary
# (data/licenses.json); the built-in map stays as the pre-1.1 fallback.
lic_json <- local({
  f <- file.path(root, "data", "licenses.json")
  if (file.exists(f)) fromJSON(f, simplifyVector = FALSE) else list()
})
lic_label <- c(
  snb  = "SNB (non-commercial, attribution)",
  kof  = "KOF / CC BY 4.0",
  fso  = "FSO (free reuse, attribution)",
  seco = "SECO open data"
)

# schema 1.1: a curated string may be bare, an i18n label object, or (source)
# an object carrying one. One tolerant read for all of them.
# schema 1.1: `concept` may be a bare "Group / Leaf" string or an object
# carrying that string plus the resolved i18n leaf. The grouping logic wants
# the English "Group / Leaf" either way.
conc_en <- function(x) if (is.list(x)) (x$en %||% "") else (x %||% "")
disp <- function(x) {
  if (is.null(x) || length(x) == 0) return("")
  if (is.character(x)) return(as.character(x)[1])
  if (is.list(x)) {
    if (!is.null(x$name)) return(disp(x$name))
    return(as.character(if (!is.null(x$en)) x$en else x[[1]])[1])
  }
  as.character(x)[1]
}
# pull a field, falling back to "" / English title.
g  <- function(x, f) disp(x[[f]])
ti <- function(x)    disp(x$title)
es <- function(s) gsub("|", "\\|", as.character(s), fixed = TRUE)  # escape table pipes

# split "Group / Leaf" into top-level group (everything before the FIRST " / ").
top_group <- function(concept) {
  i <- regexpr(" / ", concept, fixed = TRUE)
  if (i < 0) concept else substr(concept, 1, i - 1)
}
leaf_of <- function(concept) {
  i <- regexpr(" / ", concept, fixed = TRUE)
  if (i < 0) "" else substr(concept, i + 3, nchar(concept))
}

rows <- lapply(cat, function(x) {
  concept <- conc_en(x[["concept"]])
  data.frame(
    group   = top_group(concept),
    leaf    = leaf_of(concept),
    concept = concept,
    id      = g(x, "id"),
    title   = ti(x),
    source  = g(x, "source"),
    freq    = g(x, "frequency"),
    cover   = paste0(g(x, "start"), "..", g(x, "end")),
    license = { lc <- g(x, "license")
                if (!is.null(lic_json[[lc]])) disp(lic_json[[lc]]$name)
                else if (lc %in% names(lic_label)) lic_label[[lc]] else lc },
    canon   = isTRUE(x$canonical),
    stringsAsFactors = FALSE
  )
})
df <- do.call(rbind, rows)
df <- df[order(df$group, df$leaf, !df$canon, df$id), ]

# preferred group order (from docs/concepts.md); unknown groups appended.
group_order <- c(
  "National accounts", "Prices", "Labour", "Money & banking",
  "Interest rates & yields", "Exchange rates", "External sector",
  "Business cycle & sentiment", "Financial markets", "SNB policy & forecasts",
  "Payment systems", "Tourism", "Population & demographics"
)
groups <- unique(df$group)
groups <- c(intersect(group_order, groups), setdiff(groups, group_order))

lines <- c(
  "# Catalog",
  "",
  "<!-- GENERATED by dev/build_catalog_md.R from data/catalog.json. Do not edit by hand. -->",
  "",
  paste0("Human-readable overview of all **", nrow(df),
         "** datasets in the dataseries catalog, grouped by concept. Canonical ",
         "datasets are listed first within each concept; alternates follow."),
  "",
  paste0("See [`docs/concepts.md`](docs/concepts.md) for the concept tree and ",
         "canonical/alternate decisions, and [`docs/principles.md`](docs/principles.md) ",
         "for the curation principles."),
  ""
)

for (grp in groups) {
  gdf <- df[df$group == grp, ]
  lines <- c(lines, paste0("## ", grp), "")
  lines <- c(lines,
    "| ID | Title | Source | Frequency | Coverage | License |",
    "|---|---|---|---|---|---|")
  for (i in seq_len(nrow(gdf))) {
    r <- gdf[i, ]
    title <- es(r$title)
    if (!r$canon) title <- paste0(title, " _(alt)_")
    lines <- c(lines, paste0(
      "| `", r$id, "` | ", title, " | ", es(r$source), " | ",
      es(r$freq), " | ", es(r$cover), " | ", es(r$license), " |"))
  }
  lines <- c(lines, "")
}

writeLines(lines, out_path)
cat("Wrote", out_path, "(", nrow(df), "datasets,", length(groups), "groups )\n")
